name: Penville Projects
favicon: null
layout_spectrum: 1
typography_spectrum: 0
title: Penville Wine
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-74862623-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f0ffff'
    - '#060709'
    - '#006b57'
    - '#66b29c'
    - '#d76700'
  brandStrength: 0.9163543286267668
  lightness: 0.6980825844220817
  saturation: 0.125
  rhythmicContrast: 0.25
purpose: []
